### ISSUE TITLE
modeling example

### ISSUE THREAD

**Issue by grudloff** [pyrocko/lightguide#5]
Hello! I am looking to simulate earthquake data of a DAS array. From what I can gather this is done through gf.py, could you point me to an example of the usage?

**Comment by miili** [comment]
Hi there,

please have a look into modelling with pyrocko:

https://pyrocko.org/docs/current/topics/pyrocko-gf.html

For forward modelling strain along a cable (beta ☠️) change the `Target` for a `lightguide.gf.Fiber` and use the engine from `lightguide.gf.LocalEngine`, point and finite sources can be taken from `pyrocko.gf`.

The approach is a simple finite difference solution for strain from axial-displacement (_u_) along the cable.

**Comment by grudloff** [comment]
Got it! thanks
